version: "2.0"
services:
  app:
    build: .
    volumes:
      - ./src:/code
    ports:
      - 8000:8000
    # app = name of image django=tag
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000